version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      cargo-dependencies:
        patterns:
          - "*" # 将所有依赖更新合并到一个 PR 里
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions-dependencies:
        patterns:
          - "*" # 将所有依赖更新合并到一个 PR 里
